### ISSUE TITLE
no tokenization or preprocessing

### ISSUE THREAD

**Issue by niekveldhuis** [LSYS/LexicalRichness#2]
Dear Lucas, thanks for putting this together. I am using your module for text data in Sumerian (an ancient language). This data is tokenized (and lemmatized) and does not work well with the standard preprocessor. I have adapted your code to replace the use_TextBlob option with a use_tokenizer option, with default use_tokenizer = False. This default option accepts a list of tokens and does no preprocessing. The option use_tokenizer = True accepts a string and will do the default preprocessing and tokenizing. TextBlob is not useful to me, so I removed that.
I am using this in my [Computational Assyriology](http://github.com/niekveldhuis/compass) project (the package is currently used in Chapter 3 - very much a work in progress!) and of course I do credit you and give a link to the page at PyPi. Niek

**Comment by LSYS** [comment]
Hi Professor Niek, sounds like a good idea to include the option to accept
a list of tokens without preprocessing. I overlooked this. Happy to hear
that the package is useful. Regards, Lucas
