### ISSUE TITLE
Add voc-D measure

### ISSUE THREAD

**Issue by LSYS** [LSYS/LexicalRichness#42]
Add `voc-D` measure of lexical richness (robust to varying text length).

Reference: https://www.researchgate.net/publication/283149921_Measuring_Vocabulary_Diversity_Using_Dedicated_Software

**Comment by tusharkulkarni008** [comment]
may I work on  this issue

**Comment by LSYS** [comment]
hi @tusharkulkarni008, thanks so much for your interest in this project.

I do have a working version of this on my local repo. Still hashing out some minor issues in docstrings, etc.

If you are interested in Hacktoberfest, please check out issues #43 and #45.
