### ISSUE TITLE
Add example use cases of `LexicalRichness`

### ISSUE THREAD

**Issue by LSYS** [LSYS/LexicalRichness#45]
Would be nice to have more examples of [`LexicalRichness`](https://github.com/LSYS/LexicalRichness) use cases to the [`readme.rst`](https://github.com/LSYS/LexicalRichness#example-use-cases).

To contribute, add your use case of `LexicalRichness` to the [`readme`](https://github.com/LSYS/LexicalRichness#example-use-cases). See this [project on American news](https://github.com/notnews/unreadable_news) for an example of a medium-sized project. (Yours can be substantially smaller)

* [ ] Find some real-world text data (e.g., news data, song lyrics, school essays, etc.)
* [ ] Retrieve some measures of lexical richness from the text using `LexicalRichness`
* [ ] Find some cool insight or make a cool plot
* [ ] Add link to the notebook/repo/blog in this readme with a short write-up, plus your cool exhibit (e.g. a plot) (see https://github.com/LSYS/LexicalRichness#example-use-cases for an example)

Happy to discuss small use case ideas on [discord](https://discord.com/invite/hacktoberfest) or on Gitter [![Gitter](https://img.shields.io/gitter/room/lsys/lexicalrichness?style=plastic)](https://gitter.im/LSYS/lexicalrichness).

**Comment by Karthik-PM** [comment]
can you assign me this issue please

**Comment by LSYS** [comment]
@Karthik-PM, thank you for indicating your interest in this issue. Multiple people can work on this and add their own use cases.

**Comment by LSYS** [comment]
@Karthik-PM, assigned you to it

**Comment by a-1an** [comment]
Hi, can i try this too?

**Comment by g-hurst** [comment]
This seems pretty neat! I would love to work on this too!

**Comment by LSYS** [comment]
Sure @g-hurst give it a go. Please ping me if you need more clarification.

**Comment by LSYS** [comment]
Closed in [v0.3.0 Release](https://github.com/LSYS/LexicalRichness/releases/tag/v0.3.0).
